### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sh1va73** [aress31/xmlrpc-bruteforcer#3]
I get this error , any ideas?

Traceback (most recent call last):
  File "xmlrpc-bruteforcer.py", line 227, in <module>
    main()
  File "xmlrpc-bruteforcer.py", line 204, in main
    queue = reader(wordlist, chunks_size, verbose)
  File "xmlrpc-bruteforcer.py", line 162, in reader
    chunk = list(islice(wordlist, chunks_size))
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 933: invalid continuation byte

**Comment by foozzi** [comment]
How to repeat this error? what data do you use a hacker?)
